### ISSUE TITLE
Browser is caching frontend

### ISSUE THREAD

**Issue by rstens** [bcgov/ppr-deprecated#110]
When a new version of the front-end is deployed, it is not showing up in the browser. The browser is aggressively caching, neither F5 nor CTRL-R will load the new page. Using the browser in incognito mode will load the new page.
> **Comments:** 
> 
> 
> 
> **Type:** Task
> **Status:** Backlog
> **Priority:** High
> **Resolution:** 
> **Assignee:**

**Comment by bryan-gilbert** [comment]
This was fixed in PR #49 by the removal of the service worker.
We included a service worker because we found one in the lear project, which was used as the basis of our first "hello world" application.
As noted having the service worker in our code created a caching problem that prevents a user from seeing any changes.  The only workaround was to learn how to dive deeply into the browser settings and disable the ppr service worker. 
For more about service workers see https://developers.google.com/web/fundamentals/primers/service-workers

Service workers are meant to solve performance issues in the delivery of an application in production.  Since we are not yet in production and since we have not yet encountered any performance problems we will not need to consider the addition of a service worker for some time.
