### ISSUE TITLE
404 error while submitting a search for a Registration Number

### ISSUE THREAD

**Issue by rstens** [bcgov/ppr-deprecated#470]
On https://dev.bcregistry.ca/cooperatives/ppr/search I submitted a search ("123456A") and got a 404 error.
I repeated the same action again and the search executed normally.

This seems to be an unwanted race condition.

**Sentry** reported this as follows:
New alert from personal-property-registry in Dev 
ISSUE
error 	In search page catch on do search. Er...

ID: 64292bb7b85d44638618ae8f94c2978a
Feb. 12, 2020, 10:45:58 p.m. UTC
Request
URL	https://test.bcregistry.ca/cooperatives/ppr/search

User
IP Address:	142.36.253.133

Message
In search page catch on do search. Error with registration number search - Error: Request failed with status code 404
Tags
•	browser = Chrome 80.0.3987 
•	browser.name = Chrome 
•	environment = Dev 
•	level = error 
•	logger = console 
•	os = Windows 10 
•	os.name = Windows 
•	user = ip:142.36.253.133 
•	url = https://test.bcregistry.ca/cooperatives/ppr/search 

[Sentry Link](https://sentry.io/organizations/bc-government-registries/issues/1511464251/?environment=Dev&referrer=alert_email)

**Comment by bryan-gilbert** [comment]
Thanks for the report and the details.  The search page and the search result page will soon have a completely new flow due to the addition of payment.  This means the code that created the problem you reported on will no longer exist.  Let's keep this issue open until the new code lands.  then we can assess whether this issue needs further attention.
